import { NextResponse } from 'next/server';
import { adminDb } from '@/lib/firebase-admin'; // ⚠️ 注意：Webhook 在背景執行，建議使用 firebase-admin 繞過前端權限

export async function POST(req: Request) {
  try {
    // PayDollar DataFeed 發送的是 Form Data
    const formData = await req.formData();
    
    const successcode = formData.get('successcode'); // '0' 代表成功
    const orderRef = formData.get('Ref') as string;  // 我們當初送出的訂單編號 (R-tenantId-timestamp)
    const payRef = formData.get('PayRef');           // PayDollar 的交易序號
    const amount = formData.get('Amt');              // 實際交易金額

    // 1. 檢查是否付款成功
    if (successcode !== '0') {
      console.warn(`PayDollar Webhook: Payment failed for Order ${orderRef}`);
      return new NextResponse('OK', { status: 200 }); // 即使失敗也要回傳 200 OK，否則 PayDollar 會一直重試
    }

    if (!orderRef) {
      return new NextResponse('Missing Order Ref', { status: 400 });
    }

    // 2. 從 orderRef 中解析出 tenantId (格式: R-tenantId-timestamp)
    const parts = orderRef.split('-');
    const tenantId = parts[1];

    if (!tenantId) {
      return new NextResponse('Invalid Order Ref', { status: 400 });
    }

    // 3. 處理財務核銷邏輯 (更新 Firestore)
    const tenantRef = adminDb.collection('tenants').doc(tenantId);
    const tenantDoc = await tenantRef.get();

    if (!tenantDoc.exists) {
      console.error(`PayDollar Webhook: Tenant ${tenantId} not found`);
      return new NextResponse('OK', { status: 200 });
    }

    const tenantData = tenantDoc.data();
    const currentAmountDue = tenantData?.amountDue || 0;
    const paidAmount = Number(amount) || 0;

    // ★ 扣抵欠費並生成正式收據
    const batch = adminDb.batch();

    // 更新租客欠款餘額 (確保不會變成負數)
    const newAmountDue = Math.max(0, currentAmountDue - paidAmount);
    batch.update(tenantRef, {
      amountDue: newAmountDue,
      updatedAt: new Date()
    });

    // 產生系統收據 (Receipt)
    const receiptRef = adminDb.collection('documents').doc();
    batch.set(receiptRef, {
      type: 'Receipt',
      status: 'Paid',
      isAutoGenerated: true,
      formData: {
        tenantId: tenantId,
        tenantName: tenantData?.name || '',
        totalAmount: paidAmount,
        totalReceived: paidAmount,
        items: [{ description: '線上刷卡繳費 (PayDollar)', amount: paidAmount }],
        orderRef: orderRef,
        gatewayRef: payRef,
        paymentMethod: 'PayDollar',
        docDate: new Date().toISOString().split('T')[0]
      },
      createdAt: new Date(),
      updatedAt: new Date()
    });

    await batch.commit();
    console.log(`✅ Order ${orderRef} processed successfully. Paid: $${paidAmount}`);

    // PayDollar 要求回傳 'OK' 以確認收到 DataFeed
    return new NextResponse('OK', { status: 200 });

  } catch (error: any) {
    console.error('PayDollar Webhook Error:', error);
    return new NextResponse('Webhook Error', { status: 500 });
  }
}
